### ISSUE TITLE
Not compatible with jdk on macos

### ISSUE THREAD

**Issue by zhangjiayin** [tigerfintech/openapi-java-sdk#4]
https://github.com/tigerfintech/openapi-java-sdk/blob/00e9d6d3f4c88ecf0ac3e219880382b300583d46/src/main/java/com/tigerbrokers/stock/openapi/client/util/NetworkUtil.java#L24-L27

ref:https://stackoverflow.com/questions/10962072/get-mac-address-in-java-using-gethardwareaddress-non-deterministic

**Comment by lijiawen** [comment]
fixed in latest sdk version
